### ISSUE TITLE
Using themes downloaded via package control

### ISSUE THREAD

**Issue by joonro** [facelessuser/ThemeScheduler#10]
Hi,

Thanks for the great package - I was wondering if it is possible to use themes downloaded via package control? I looked at the documentation but couldn't find the info. Thank you so much.

**Comment by facelessuser** [comment]
Yeah, you can use themes from Package Control.  Package Control will usually install the packages as zip files in `Installed Packages` instead to the `Packages` folder, but you treat them as if they are stored in the Packages folder unzipped.  Sublime handles the abstraction.

So if I had a color scheme in a zipped package at `Installed Packages/Mypackage.sublime-package/mycolorscheme.tmTheme`, I would specify it as `Packages/Mypackage/mycolorscheme.tmTheme`.

So yeah, any installed ui theme or color scheme should work.

**Comment by joonro** [comment]
Thanks a lot - it works. It would be great if this information is included in the documentation.

**Comment by facelessuser** [comment]
> Thanks a lot - it works. It would be great if this information is included in the documentation.

I'll try and remember, but pull requests are welcome :wink:.
