### ISSUE TITLE
Allow ThemeScheduler to change .sublime-theme as well?

### ISSUE THREAD

**Issue by MattDMo** [facelessuser/ThemeScheduler#5]
Hi Isaac, 
I really like the idea of being able to set the color scheme `.tmTheme` for arbitrary times of the day, but oftentimes the `.sublime-theme` (like [Theme - Soda](https://sublime.wbond.net/packages/Theme%20-%20Soda)) goes along with the color scheme, and should be switched at the same time. Would there be a way to add that in as well? Of course, to do that you'd need to switch the current config option `"theme"` to `"color_scheme"` the way it is in `Preferences.sublime-settings`, and use `"theme"` for the `.sublime-theme` file, and this would completely break any existing installations. Perhaps run a regex on the contents of `"theme"` and act according to whether it ends with `.tmTheme` or `.sublime-theme`?

Anyways, just a thought. Thanks for yet another great plugin!

Regards,
Matt

**Comment by christarazi** [comment]
I've found that setting a theme (besides Sublime's default) in the "Preferences.sublime-settings" file fixes the glitching tabs when changing `ui_themes`.

Here's an example:

### Preferences.sublime-settings ###

```json
{
	"font_face": "Source Code Pro Medium",
	"font_size": 16,
	"quick_panel_small": true,
	"scroll_speed": 0.0,
	"sidebar_row_padding_medium": true,
	"sidebar_size_14": true,
	"spell_check": true,
	"status_bar_brighter": true,
	"tabs_small": true,
	"theme": "Spacegray Light.sublime-theme"
}
```

As you can see, I set
```json
theme: "Spacegray Light.sublime-theme"
```
to default to fix tabs from glitching. I tried setting it with both of the themes I'm using and they worked perfectly. I can't say if this works for every combination.

### ThemeScheduler.sublime-settings ###

```json
{
    "enabled": true,
    "themes": 
	[
		{
			"ui_theme": "Spacegray Light.sublime-theme",
			"theme": "Packages/Tomorrow Color Schemes/Tomorrow.tmTheme",
			"time": "8:00"
		},
		{
			"ui_theme": "Afterglow-blue.sublime-theme",
    		"theme": "Packages/Tomorrow Color Schemes/Tomorrow-Night-Eighties.tmTheme",
    		"time": "17:00"
		}
	]
}
```

Thought this would help someone in the same scenario as me.
