### ISSUE TITLE
Typo in `ThemeScheduler.py`

### ISSUE THREAD

**Issue by jrappen** [facelessuser/ThemeScheduler#7]
[Line 610 in ThemeScheduler.py](https://github.com/facelessuser/ThemeScheduler/blob/65e0054834a9d8ca5d2201e1b4c0c5b1334e3c7a/ThemeScheduler.py#L610) should be:

```python
log("Loading...")
```

instead of

```python
log("ThemeScheduler: Loading...")
```

because compare [Line 50 in ThemeScheduler.py](https://github.com/facelessuser/ThemeScheduler/blob/65e0054834a9d8ca5d2201e1b4c0c5b1334e3c7a/ThemeScheduler.py#L50)

**Comment by jrappen** [comment]
same goes for [Line 624 in ThemeScheduler.py](https://github.com/facelessuser/ThemeScheduler/blob/65e0054834a9d8ca5d2201e1b4c0c5b1334e3c7a/ThemeScheduler.py#L624)

**Comment by facelessuser** [comment]
Yup.  I'll try and get to that when I get a chance.  Pull requests are also good :wink:.
